
// Generated helper templates
// Generated items
// FreshBooks.Api\src\FreshBooks.Api\FreshBooksClient.partial.cs
// FreshBooks.Api\src\FreshBooks.Api\BaseResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\TimeEntryUpdateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\TimeEntryUpdateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\TimeEntryListResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\TimeEntryListRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\TimeEntryGetResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\TimeEntryGetRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\TimeEntryDeleteResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\TimeEntryDeleteRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\TimeEntryCreateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\TimeEntryCreateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\TaxUpdateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\TaxUpdateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\TaxListResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\TaxListRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\TaxGetResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\TaxGetRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\TaxDeleteResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\TaxDeleteRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\TaxCreateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\TaxCreateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\TaskUpdateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\TaskUpdateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\TaskListResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\TaskListRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\TaskGetResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\TaskGetRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\TaskDeleteResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\TaskDeleteRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\TaskCreateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\TaskCreateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\SystemCurrentResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\SystemCurrentRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\StaffUpdateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\StaffUpdateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\StaffListResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\StaffListRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\StaffGetResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\StaffGetRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\StaffDeleteResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\StaffDeleteRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\StaffCurrentResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\StaffCurrentRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\StaffCreateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\StaffCreateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ReportGetProfitDetailsResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ReportGetProfitDetailsRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ReportGetInvoiceDetailsResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ReportGetInvoiceDetailsRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ReportGetExpenseDetailsResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ReportGetExpenseDetailsRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ReportGetEstimateDetailsResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ReportGetEstimateDetailsRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ReportGetClientDetailsResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ReportGetClientDetailsRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\RecurringUpdateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\RecurringUpdateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\RecurringListResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\RecurringListRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\RecurringLinesUpdateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\RecurringLinesUpdateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\RecurringLinesDeleteResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\RecurringLinesDeleteRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\RecurringLinesAddResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\RecurringLinesAddRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\RecurringGetResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\RecurringGetRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\RecurringDeleteResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\RecurringDeleteRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\RecurringCreateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\RecurringCreateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ReceiptUpdateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ReceiptUpdateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ReceiptGetRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ReceiptDeleteResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ReceiptDeleteRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ReceiptCreateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ReceiptCreateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ProjectUpdateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ProjectUpdateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ProjectListResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ProjectListRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ProjectGetResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ProjectGetRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ProjectDeleteResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ProjectDeleteRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ProjectCreateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ProjectCreateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\PaymentUpdateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\PaymentUpdateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\PaymentListResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\PaymentListRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\PaymentGetResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\PaymentGetRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\PaymentDeleteResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\PaymentDeleteRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\PaymentCreateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\PaymentCreateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\LanguageListResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\LanguageListRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ItemUpdateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ItemUpdateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ItemListResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ItemListRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ItemGetResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ItemGetRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ItemDeleteResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ItemDeleteRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ItemCreateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ItemCreateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceUpdateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceUpdateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceSendBySnailMailResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceSendBySnailMailRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceSendByEmailResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceSendByEmailRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceSendByEmailCustomEmailResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceSendByEmailCustomEmailRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceListResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceListRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceLinesUpdateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceLinesUpdateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceLinesDeleteResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceLinesDeleteRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceLinesAddResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceLinesAddRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceGetPDFRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceGetResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceGetRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceDeleteRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceCreateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\InvoiceCreateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\GatewayListResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\GatewayListRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ExpenseUpdateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ExpenseUpdateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ExpenseListResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ExpenseListRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ExpenseGetResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ExpenseGetRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ExpenseDeleteResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ExpenseDeleteRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ExpenseCreateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ExpenseCreateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\EstimateUpdateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\EstimateUpdateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\EstimateSendByEmailRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\EstimateSendByEmailCustomEmailRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\EstimateMarkAsSentResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\EstimateMarkAsSentRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\EstimateListResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\EstimateListRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\EstimateGetPDFRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\EstimateGetResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\EstimateGetRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\EstimateDeleteResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\EstimateDeleteRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\EstimateCreateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\EstimateCreateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\EstimateAcceptResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\EstimateAcceptRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\EmailTemplateUpdateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\EmailTemplateUpdateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\EmailTemplateListResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\EmailTemplateListRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\EmailTemplateGetResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\EmailTemplateGetRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\DefaultTermsUpdateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\DefaultTermsUpdateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\DefaultTermsListResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\DefaultTermsListRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\DefaultTermsGetResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\DefaultTermsGetRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\CurrencyListResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\CurrencyListRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ContractorUpdateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ContractorUpdateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ContractorListResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ContractorListRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ContractorGetResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ContractorGetRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ContractorDeleteResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ContractorDeleteRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ContractorCreateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ContractorCreateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ClientUpdateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ClientUpdateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ClientListResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ClientListRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ClientGetResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ClientGetRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ClientDeleteResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ClientDeleteRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\ClientCreateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\ClientCreateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\CategoryUpdateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\CategoryUpdateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\CategoryListResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\CategoryListRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\CategoryListHierarchyResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\CategoryListHierarchyRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\CategoryGetResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\CategoryGetRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\CategoryDeleteResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\CategoryDeleteRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\CategoryCreateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\CategoryCreateRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\CallbackVerifyResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\CallbackVerifyRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\CallbackResendTokenResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\CallbackResendTokenRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\CallbackListResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\CallbackListRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\CallbackDeleteResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\CallbackDeleteRequest.cs
// FreshBooks.Api\src\FreshBooks.Api\CallbackCreateResponse.cs
// FreshBooks.Api\src\FreshBooks.Api\CallbackCreateRequest.cs
